language: python
python:
- '2.7'
install: pip install -r requirements/ci.txt
script: ./test.sh
env:
  global:
  - SECRET_KEY="test"
  - ADMIN_USER="foo@bar.bz"
  - secure: GtqTbo6EX4+PkxSJk+++xftWhg+KuY02GXK8x4aKKZoxL8DVOAgSoIVSo63AIz+xxR7iBlG+8KBm52km9sNVA7ybOfTa9k6AaOv+DolI0RfPFjPYcY5Yi8vKHbPg5fss3cORZ4hcPstQ1JkLXmPqalkdWrniDAfsZWH1yhQXaRQ=
  - secure: majk411hPRV9swixQLtA8d7HVutufMi9Ey+2pQxcWnJPPvfBFbfg3MuCFVBYtESbhmTAPLk7SP/x1jusJbhPSfmjaj1ys167x2stnfGFrMXKGnGwB3LgAseTnnzJZR/tr2s+SKLygibGiegwTftOnp2Bjs9M33I+DMxOudlwX7E=
  - secure: AYEt/cJHKuU/RRuguzk61Av/VQMoK3kWdr8mCghKaQi/C/wQhKZ+V33OLdUKwK640Mj+BMORBUKLhBimFJxmceoRLUtLyu8EJA+Pi5grJVOtP3mPsLdvJEreEoyQ1lf5hSrgddEI6mSxcBlcC+h9w4RxM92oJRCLUpGFz4GSl1Q=
  - secure: guo48FUSS9AV0qWifTjkMZMQpOydPfnUOwM0xbDMIwMmmHFJLbCZhuNrowytNlHORIsBo0YhCxpyUxt8UHqbUR8sbK5ileBzIBXNgniHXdHwT/6pFsZbGybs0pKEeUUQrwknCMJs6ePG1OXH/swBqZr+AQ5WY6z4LbnK7Magj6Y=
  - secure: Q0PfEdRxdzu6oPUaGBWaZr2dsJX6OXm6sovrIqpIaIw6GkF1H8YSfjrzGFpN/rFrSnBKmFkXlLqfmVylCab7iFd1/PeoEOYr+lW9s6CGcC/ElKHqgWaZjFUYnqF8WEXnLh0EmJv8yITBsAb6SSuOtgelpRHAC5TPgXF9SnMhNU8=
branches:
  only:
  - ci
  - stage
addons:
  sauce_connect:
    username: geaden
    access_key:
      secure: GFOumOR40ho9gjVa37R1H/F1PpFUH+dQ38Nejy5cEoWI3B1nOaA6D26erBOdnlV9gC4lcXMPt+QMCDjGQsLI4fG3ioVmVFYF4OLGKUVgKF3Y5vYTcLnOJryJuENWg+SyYwKQE1QoMJJTsSxDx0j0ZaZUYcWN+YtcxgvLMnFXD/w=
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
deploy:
  provider: heroku
  api_key:
    secure: P7GIs9un1v9zBUbKBun2/V4aFGIAjV81Q1HRP9kN4jP67hrrexDe2cXZpKpp/DA8uME1ITJ6EDOvjEHEhnZEfq3YOGRogxWgKHdBJ8ky/QZYXQ4/xKMZsRtC5qR03x+/Dp0XOlJ0gFam4ig6eTZaIY4lF9n4O0fDjpYoqt1NHgM=
  run:
    - "python bookmarks/manage.py migrate"
  app: immense-oasis-2242
  on: stage
